steps:

  # Install node packages
  - name: 'gcr.io/cloud-builders/npm:14.15.1'
    dir: 'portfolio'
    args: [ 'install' ]

  # Build productive files
  - name: 'gcr.io/cloud-builders/npm'
    dir: 'portfolio'
    args: [ 'run', 'build', '--prod' ]

  # Deploy to google cloud app egnine
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    args: ['app', 'deploy', '--version=prod']
    timeout: '1600s'
    